version: '3.8'
services:
  portfolio:
    build: .
    ports:
      - "8080:8080"
    env_file:
      - ./.env
    volumes:
      - ./public:/var/www/html:ro
      - ./portfolio.db:/app/portfolio.db:rw
      - ./.env:/app/api/.env:ro
    restart: unless-stopped
    
    # Security configurations
    security_opt:
      - no-new-privileges:true
    tmpfs:
      - /tmp
      - /app/api/logs
      - /var/lib/nginx/logs
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
      - NET_BIND_SERVICE
    
    # Resource limits
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 128M
    
    # Health check
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    
    # Network security
    networks:
      - portfolio-network
    dns:
      - 8.8.8.8
      - 8.8.4.4

  

networks:
  portfolio-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16

